http:
  routers:
    ${PROJECT_NAME}-wp:
      rule: "Host(`${DOMAIN}`)"
      entryPoints:
        - websecure
      service: ${PROJECT_NAME}-wp
      tls: {}
    
    ${PROJECT_NAME}-pma:
      rule: "Host(`pma.${DOMAIN}`)"
      entryPoints:
        - websecure
      service: ${PROJECT_NAME}-pma
      tls: {}

  services:
    ${PROJECT_NAME}-wp:
      loadBalancer:
        servers:
          - url: "http://${PROJECT_NAME}_wp:80"
    
    ${PROJECT_NAME}-pma:
      loadBalancer:
        servers:
          - url: "http://${PROJECT_NAME}_pma:80"

tls:
  stores:
    default:
      defaultCertificate:
        certFile: /certs/cert.pem
        keyFile: /certs/key.pem

